project.name_1=My Project 479
project.name_1.token=AIzaSyAXHRNSvnqSkj_CuJyKsxS31UIjBuFrc0E
project.name_2=My Project 48128
project.name_2.token=AIzaSyAXHRNSvnqSkj_CuJyKsxS31UIjBuFrc0E
project.name_3=My Project 63906
project.name_3.token=AIzaSyAzk8mEoOigzmUknRB7jAaAcJw3wNmioqEesc