CREATE TABLE IF NOT EXISTS playground_cases (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  source ENUM('traffic', 'conversation') NOT NULL,
  source_ref VARCHAR(64) NOT NULL,
  case_mode ENUM('contextual', 'wire') NOT NULL,
  trace_context JSON NOT NULL,
  prompt_id VARCHAR(36) NULL,
  prompt_mode_default ENUM('saved', 'draft') NOT NULL DEFAULT 'draft',
  prompt_input JSON NOT NULL,
  provider_config JSON NOT NULL,
  baseline_output JSON NULL,
  raw_evidence JSON NOT NULL,
  tags JSON NULL,
  notes TEXT NULL,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  created_by VARCHAR(100) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_source_ref (source, source_ref),
  INDEX idx_prompt_id (prompt_id),
  INDEX idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS playground_runs (
  id VARCHAR(36) PRIMARY KEY,
  case_id VARCHAR(36) NOT NULL,
  prompt_mode ENUM('saved', 'draft') NOT NULL,
  prompt_id VARCHAR(36) NULL,
  prompt_snapshot JSON NULL,
  provider_config_snapshot JSON NOT NULL,
  input_snapshot JSON NOT NULL,
  output_snapshot JSON NULL,
  comparison_snapshot JSON NULL,
  model_name VARCHAR(120) NULL,
  provider VARCHAR(50) NULL,
  status ENUM('completed', 'failed') NOT NULL DEFAULT 'completed',
  executed_by VARCHAR(100) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_case_created_at (case_id, created_at),
  INDEX idx_created_at (created_at),
  CONSTRAINT fk_playground_runs_case FOREIGN KEY (case_id) REFERENCES playground_cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
