-- =====================================================================
-- llm_usage_rollup_sources.model_name 死列清理（一次性）
-- =====================================================================
-- ⚠️ 不要直接执行。确认后手动跑。
--
-- 这列是 2026-08-23 的一次事故残留，不是任何一版代码的 schema 契约：
-- 当时在 feat/llm-request-observability（那一版打算给 LLM Cost 折线加模型维度）
-- 上对**生产库**跑了一遍 persistence 用例。persistence 每个函数入口都会跑
-- ensureXiaoni*Schema，里面的 guarded ADD COLUMN 就这么落到了 qqbot_db 上，
-- 而那个分支从没部署。同一次事故还把 codex_provider_usage_events 提前改了名
-- （已手工回滚，见 xiaoni-recall-regression.realdb.test.js 文件头的警示）。
--
-- 之后 main 的 d4c0a354 走了相反的路：召回精排/展开这类**不骑主请求前缀**的独立
-- 小请求，整个排除出 LLM Cost 聚合，而不是留在图里按模型拆线。按模型分组因此没有
-- 了需求方——2026-09-08 实测，排除后仍进聚合的五个源（main_slices / cache_heartbeat
-- / subconscious_fork / compression_fork / image_vision_fork）模型清一色
-- claude-opus-4-6，分组只会画出一条线。
--
-- 现状（2026-09-08 实测）：118597 行，model_name **全部为 NULL**。没有任何代码写它、
-- 读它。main 的 CREATE TABLE 里也没有这一列——所以任何新库都不会有它，只有这一个
-- 生产库带着它。
--
-- 库：主栈 PostgreSQL（worktree 也连主工作区主栈 DB）。
-- =====================================================================

-- ---------------------------------------------------------------------
-- 执行前复查：确认它确实全空（有非 NULL 就先停下来查清楚谁写的）
-- ---------------------------------------------------------------------
--   SELECT count(*) AS total,
--          count(model_name) AS non_null
--   FROM llm_usage_rollup_sources;
--   -- 期望 non_null = 0

-- ---------------------------------------------------------------------
-- 删列。DROP COLUMN 只改系统目录（把列标记成 dropped），不重写表，瞬时完成；
-- 但仍要拿 ACCESS EXCLUSIVE，跑之前确认没有长事务压着这张表。
-- ---------------------------------------------------------------------
-- ALTER TABLE llm_usage_rollup_sources DROP COLUMN IF EXISTS model_name;

-- ---------------------------------------------------------------------
-- 不需要 bump USAGE_ROLLUP_VERSION。
-- 版本门是用来触发**全量重建回填**的，而这里没有任何数据要回填——删的是一列 NULL。
-- 重建跑在 initializeLlmUsageRollupsIfNeeded 里、挂在每一次持久化操作的路径上，
-- 一个事务里 DELETE 两张 rollup 表 + 七源全量 UNION、全程持 advisory lock，
-- 所有服务排队等，主 loop 可能停等数分钟。为删一列空列付这个代价不值。
-- ---------------------------------------------------------------------
