#!/usr/bin/env bash
#
# Helper to prepare Playwright/MCP inside WSL2.
# - Installs common Chromium deps
# - Writes a convenience env file that forces --no-sandbox flags
# - Provides guidance for MCP bridge usage

set -euo pipefail

REQUIRED_PACKAGES=(
  ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0
  libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1
  libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0
  libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1
  libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils
)

ENV_DIR="${HOME}/.config/qqbot"
ENV_FILE="${ENV_DIR}/playwright-wsl.env"

print_step() {
  printf '\n==== %s ====\n' "$1"
}

ensure_wsl() {
  if ! grep -qi microsoft /proc/version 2>/dev/null; then
    echo "This script is intended to run inside WSL2. Continuing anyway..."
  fi
}

install_packages() {
  print_step "Installing Chromium/Playwright runtime libraries"
  sudo apt-get update
  sudo apt-get install -y "${REQUIRED_PACKAGES[@]}"
}

write_env_file() {
  mkdir -p "${ENV_DIR}"
  cat > "${ENV_FILE}" <<'EOF'
# Auto-generated by scripts/setup_playwright_wsl.sh
# Ensures Playwright/Chromium launches inside constrained WSL kernels.
export PLAYWRIGHT_CHROMIUM_EXTRA_ARGS="--disable-gpu --no-sandbox --disable-setuid-sandbox"
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD="1"
# Point Playwright at the system Chromium/Edge if already installed on Windows.
# export PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH="/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
EOF
  print_step "WSL Playwright env file created"
  echo ">> ${ENV_FILE}"
  echo "Append the following line to your shell profile to activate automatically:"
  echo "  source \"${ENV_FILE}\""
}

print_mcp_notes() {
  cat <<'EOF'

Next steps:
1. Enable systemd & vsyscall emulation by adding to /etc/wsl.conf (requires Windows reboot):
   [boot]
   systemd=true

   [wsl2]
   kernelCommandLine = vsyscall=emulate

2. Install the Playwright MCP Bridge extension in your Windows browser and run the MCP
   server either on Windows (recommended) or inside WSL with `npx @playwright/mcp --extension`.
3. If you stay inside WSL, be sure to start a desktop browser on Windows so the
   extension can authorize the connection.

EOF
}

main() {
  ensure_wsl
  install_packages
  write_env_file
  print_mcp_notes
}

main "$@"
